import Head from 'next/head'
import Link from "next/link";
import { useRouter } from "next/router";

import styles from '../styles/Home.module.scss'
import { Footer, Header } from '../components/index'
// import NewsCard from "../components/NewsCard/NewsCard";
// import newsContent from '../public/locales/en/lang'

// -- IMPORTS PARA I18N 
import { useTranslation, Trans } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'


export default function Home() {
  // const { locale, locales, defaultLocale, asPath } = useRouter();
  // const { title, content } = newsContent[locale];

  const router = useRouter()
  const { t } = useTranslation('common')

  return (
    <div className={styles.head}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className={styles.container}>
        <Head>
          <title>TV</title>
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <p>
          <Trans i18nKey="blog.optimized.answer">
            Then you may have a look at{' '}
            <a href={t('blog.optimized.link')}>this blog post</a>
            .
          </Trans>
        </p>
      </div>
      );
      <Footer />
    </div>
  )
}
// or getServerSideProps: GetServerSideProps<Props> = async ({ locale })
export const getStaticProps = async ({
  locale,
}) => ({
  props: {
    ...(await serverSideTranslations(locale ?? 'es', [
      'common',
      // 'footer',
    ])),
  },
})

