import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Footer, Header } from '../components/index'

export default function Home() {
  return (
    <div className={styles.head}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />


      <main className={styles.main}>
        <h1 className={styles.title}>
          Convirtiendo ilumina a nextjs
          Recuerda que sea solo lo mínimo indispensable.
        </h1>
        <h6>test de h6</h6>
      </main>
      <Footer />
    </div>
  )
}
