import Head from 'next/head'
import HomeSection from '../components/Home/HomeSection'
import styles from '../styles/Home.module.scss'

// -- IMPORTS PARA I18N 
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

// -- LAYOUT
import HomeLayout from '../components/HomeLayout'

export default function Home() {

  return (
    <div className={styles.head}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
        <HomeSection />
      </HomeLayout>
      );
    </div>
  )
}
// or getServerSideProps: GetServerSideProps<Props> = async ({ locale })
export const getStaticProps = async ({
  locale,
}) => ({
  props: {
    ...(await serverSideTranslations(locale ?? 'es', [
      'common',
      // 'footer',
    ])),
  },
})

